global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporter
    static_configs:
      - targets:
          - "192.168.1.100:9100"
          - "192.168.1.101:9100"
          - "192.168.1.102:9100"

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: kafka-brokers-jmx
    static_configs:
      - targets:
          - "192.168.1.100:7071"
          - "192.168.1.101:7071"
          - "192.168.1.102:7071"
